# -*- coding: utf-8 -*-
"""Sentiment Analysis Using LSTM and CNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tzWc51OLJftCvOfqHvJ1sHnG6APfDDSg

-------- Note --------
1. Open Sentiment Analysis Using LSTM and CNN.ipynb using google pro
2. Upload ***function.py*** into your directory
3. Upload all models ***.h5** into your directory
4. Change judulBerita to analyse sentiment of the new text
5. Run All the codes
"""

import function

judulBerita = 'Terdakwa Kasus Jiwasraya Beri Uang Jajan Rp 100 Juta, Prediksi Harga Emas'

modelLSTM = 'lstm.h5'
modelLSTM_CNN ='lstm-cnn.h5'
modelCNN_LSTM = 'cnn-lstm.h5'

AnalysisSentiment = function.InputSentence(judulBerita,modelLSTM,modelLSTM_CNN,modelCNN_LSTM)
AnalysisSentiment.Predict()